### ISSUE TITLE
Recover from closed chan?

### ISSUE THREAD

**Issue by SeaYo** [olebedev/emitter#3]
I noticed that you commented out the recovery lines for sending to closed chan.
https://github.com/olebedev/emitter/blob/master/emitter.go#L343
When I used emitter, it errors out. What was the reason when you decide to comment them out?
Can we add them back?

Thanks,
Sea

**Comment by olebedev** [comment]
Hi @SeaYo,

the reason to comment this piece of code is to avoid _defer panic_ overhead at runtime and I supposed that you should not close listeners by self. Instead,  you could use `e.Off("<topic>", listener)` to close and unsubscribe it. Because the listener is created internally with one-way direction and the library itself should handle this case.

Could you provide your use case?

**Comment by SeaYo** [comment]
Hi @olebedev  

Thanks for the reply. 
Maybe I'm not using emitter in the correct way. My use case is that when listener subscribes to the topic, if any error occurs during the consumption of the messages, the subscriber will unsubscribe itself.

The possible reason why I got `closed chan` panic is that, when the publisher tries to publish messages, it finds 3 listeners, for example. And at the time the  publisher loop through these 3 listeners, one of them errored out and unsubscribed. So that a message was sent to a closed chan.

Referring to my implementation here if you don't mind:
https://github.com/vivowares/eywa/blob/master/pubsub/subscriber.go#L42

Am I using it in a correct way?

**Comment by olebedev** [comment]
Not exactly. There are four ways how to solve it correctly:

* You could set general middlware for emitter instance to close any listener if the sending is blocked, in other words if you stop listen it. Example:
```go
EM := emitter.New(capacity)
EM.Use("<topic>", emitter.Close) // <- emitter.Close do exactly what I described above
```
* You could put local middleware at the subscription moment for specific listener. Example:
```go
for event := range EM.On(s.Topic(), emitter.Close) {
	msg := event.String(0)
	if s.flush([]byte(msg)) != nil {
		return
	}
}
```
* You could close listener directly. Example:
```go
listener := EM.On(s.Topic())
for event := range listener {
	msg := event.String(0)
	if s.flush([]byte(msg)) != nil {
		EM.Off("*", listener) // generic topic to find specified listener anyway
		return
	}
}
```
* If you know that the topic is unique you could do this:
```go
for event := range EM.On(s.Topic()) {
	msg := event.String(0)
	if s.flush([]byte(msg)) != nil {
		EM.Off(s.Topic()) // will closed any listener for this topic
		return
	}
}
```

Is it fits in your workflow?

**Comment by SeaYo** [comment]
Wow, definitely helps!

Thank you so much!  BTW, I just found you are the author of duktape. You are awesome.

**Comment by olebedev** [comment]
You're welcome )
