### ISSUE TITLE
Callbacks-only usage not working

### ISSUE THREAD

**Issue by svera** [olebedev/emitter#4]
Hi,
thank you for this nice package. I was trying to use it following the callback-only instructions provided in the `README`, with no luck. There, you specify:

> The recipe is use emitter with zero capacity, define FlagVoid to skip sending into the listener channel and use middleware as callback

I've tried changing `FlagVoid` to `FlagSkip` and now things seem to be working. Could it be that documentation is not right at this point, or am I doing something wrong?

**Comment by olebedev** [comment]
Hi @svera,

could you please provide the code?

**Comment by svera** [comment]
Hi @olebedev,
sure! Nothing fancy here, though. I initialise the emitter in `main.go` and pass it to a struct called `Hub` when I instantiate it:

```
		e := &emitter.Emitter{}
		e.Use("*", emitter.Void)
                hb = hub.New(cfg, e, isDebugEnabled())
```

When `Hub` is instantiated, it declares a listener to `messageCreated` events:

```
h.emitter.On("messageCreated", func(event *emitable.Event) {
		log.Println("captured event")
		clients := event.Args[0].([]interfaces.Client)
		message := event.Args[1].([]byte)

		for _, cl := range clients {
			h.sendMessage(cl, message)
		}
})
```

Then, we just emit `messageCreated`events when appropiate:

```
go h.emitter.Emit("messageCreated", h.clients, h.createUpdatedRoomListMessage())
```
