### ISSUE TITLE
how to transfer object into the listener

### ISSUE THREAD

**Issue by jjhesk** [olebedev/emitter#9]
e := &ev.Emitter{}
e.Use("*", ev.Void)

e.On("main_event", func(evt *ev.Event) {
			message_like := evt.Args[0]
			js_content, _ := json.Marshal(message_like)
			fmt.Printf("\nBC mess:", js_content)
})

type Announcement struct {
	GameID     int     `json:"gid"`
	PlayerId   int64   `json:"pid"`
}

b1 := &Announcement{
		GameID:     1,
		PlayerId:   4234,
}
go ev.Emit("main_event", b1)

how to cast the type into the receive listener?

**Comment by olebedev** [comment]
b2, ok := e.Args[0].(*Announcement)

**Comment by jjhesk** [comment]
ok, thats really useful!
